/*import * as md from "react-icons/md";
import * as fa from "react-icons/fa";
import * as fa6 from "react-icons/fa6";
import * as io from "react-icons/io";
import * as io5 from "react-icons/io5";
import * as bs from "react-icons/bs";
import * as ri from "react-icons/ri";
import * as bi from "react-icons/bi";
import * as gr from "react-icons/gr";
import * as im from "react-icons/im";
import * as tb from "react-icons/tb";*/

export const iconList = [
  { name: "MdLogout", component: md.MdLogout },
  { name: "MdLogin", component: md.MdLogin },
  { name: "FaUsers", component: fa.FaUsers },
  { name: "FaClipboardList", component: fa.FaClipboardList },
  { name: "FaLayerGroup", component: fa.FaLayerGroup },
  { name: "FaBookmark", component: fa.FaBookmark },
  { name: "FaRegBookmark", component: fa.FaRegBookmark },
  { name: "IoMdShare", component: io.IoMdShare },
  { name: "MdEdit", component: md.MdEdit },
  { name: "FaRegUser", component: fa.FaRegUser },
  { name: "GrDown", component: gr.GrDown },
  { name: "GrUp", component: gr.GrUp },
  { name: "ImCheckmark", component: im.ImCheckmark },
  { name: "MdLink", component: md.MdLink },
  { name: "MdMic", component: md.MdMic },
  { name: "MdMicOff", component: md.MdMicOff },
  { name: "IoChevronDownSharp", component: io5.IoChevronDownSharp },
  { name: "MdVideocam", component: md.MdVideocam },
  { name: "MdVideocamOff", component: md.MdVideocamOff },
  { name: "MdThumbUp", component: md.MdThumbUp },
  { name: "MdArrowBackIosNew", component: md.MdArrowBackIosNew },
  { name: "MdArrowForwardIos", component: md.MdArrowForwardIos },
  { name: "BsMic", component: bs.BsMic },
  { name: "BsMicMute", component: bs.BsMicMute },
  { name: "BsCameraVideo", component: bs.BsCameraVideo },
  { name: "BsCameraVideoOff", component: bs.BsCameraVideoOff },
  { name: "IoMdClose", component: io.IoMdClose },
  { name: "MdOutlineArrowForwardIos", component: md.MdOutlineArrowForwardIos },
  { name: "IoMdWarning", component: io.IoMdWarning },
  { name: "IoIosSearch", component: io.IoIosSearch },
  { name: "FaGithub", component: fa.FaGithub },
  { name: "IoIosClose", component: io.IoIosClose },
  { name: "IoArrowBackSharp", component: io5.IoArrowBackSharp },
  { name: "IoEyeOutline", component: io5.IoEyeOutline },
  { name: "IoEyeOffOutline", component: io5.IoEyeOffOutline },
  { name: "RiDeleteBin6Fill", component: ri.RiDeleteBin6Fill },
  { name: "FaUserGroup", component: fa6.FaUserGroup },
  { name: "IoMdAdd", component: io.IoMdAdd },
  { name: "TbCrown", component: tb.TbCrown },
  { name: "FaFolder", component: fa.FaFolder },
  { name: "MdOutlineVisibility", component: md.MdOutlineVisibility },
  { name: "BiHide", component: bi.BiHide },
  { name: "FaHome", component: fa.FaHome },
  { name: "FaRegUserCircle", component: fa.FaRegUserCircle },
  { name: "IoHomeSharp", component: io5.IoHomeSharp },
  { name: "IoPersonSharp", component: io5.IoPersonSharp }
];
